Tech Spec French Translate
Phala-Network/phala-wiki pull request #37
Opened 2021-06-18 14:43 UTC by TionebErtahcnom

2021-06-18 15:41 UTC, krhougs commented
Merci

2021-06-18 15:41 UTC, krhougs commented
Merci beaucoup !

2021-06-18 15:51 UTC, krhougs requested changes

2021-06-18 15:51 UTC, krhougs commented on content/docs/_index.fr-fr.md
> +{{< button "spec" "Sécifications Techniques" >}}
Spécifications ?

2021-06-18 15:51 UTC, krhougs commented on content/docs/spec/_index.fr-fr.md
> +Ce document décrit les spécifications techniques du réseau Phala, y compris le protocole global, la structure et l'algorithme détaillés des données. Ce travail est encore en cours.
I noticed that the phase 'Phala Network' is used below.

2021-06-18 15:51 UTC, krhougs commented on content/docs/spec/_index.fr-fr.md
> +### L'Initialisation `pRuntime`
Il manques un 'de' ou non ?

2021-06-18 15:51 UTC, krhougs commented on content/docs/spec/_index.fr-fr.md
> +1. « A » et « B » connaissent chacun la clé publique de l'autre à partir de la blockchain. Ils peuvent dériver `CommKey(A, B)`;
« A » et « B » se connaissent ?

2021-06-18 16:16 UTC, TionebErtahcnom commented on content/docs/spec/_index.fr-fr.md
> +### L'Initialisation `pRuntime`
Effectivement, l'initialisation de 'pRuntime' serait mieux.

2021-06-18 16:19 UTC, TionebErtahcnom commented on content/docs/spec/_index.fr-fr.md
> +1. « A » et « B » connaissent chacun la clé publique de l'autre à partir de la blockchain. Ils peuvent dériver `CommKey(A, B)`;
Ils connaissent chacun la clés publique de l'autre. Je pense que c'est bon.

2021-06-18 16:47 UTC, TionebErtahcnom commented
Thanks @krhougs!

2021-06-19 12:32 UTC, merged

2021-06-19 13:38 UTC, h4x3rotab commented
Published to the live webiste